//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutatu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        public short id_com { get; set; }
        public short id_u { get; set; }
        public System.DateTime date { get; set; }
        public short zone_id { get; set; }
        public Nullable<short> cont_id { get; set; }
        public string content { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual zona zona { get; set; }
    }
}
