//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutatu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tatuador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tatuador()
        {
            this.tatuaje = new HashSet<tatuaje>();
        }
    
        public short id_tat { get; set; }
        public short id_u { get; set; }
        public short id_emp { get; set; }
        public string fname_tat { get; set; }
        public string sname_tat { get; set; }
        public string email_tat { get; set; }
        public string phone_tat { get; set; }
        public string style_tat { get; set; }
        public string ink_tat { get; set; }
        public bool designer_tat { get; set; }
        public string trayectory_tat { get; set; }
        public string study_tat { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tatuaje> tatuaje { get; set; }
    }
}
