//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutatu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tatuaje
    {
        public short id_tatoo { get; set; }
        public Nullable<short> id_wu { get; set; }
        public Nullable<short> id_tat { get; set; }
        public string style_tatoo { get; set; }
        public bool color_tatoo { get; set; }
        public System.DateTime date_tatoo { get; set; }
        public System.TimeSpan time_tatoo { get; set; }
        public Nullable<decimal> price_tatoo { get; set; }
        public System.DateTime shoot_date { get; set; }
    
        public virtual tatuador tatuador { get; set; }
        public virtual webuser webuser { get; set; }
    }
}
