//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutatu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public webuser()
        {
            this.tatuaje = new HashSet<tatuaje>();
        }
    
        public short id_wu { get; set; }
        public short id_u { get; set; }
        public string fname { get; set; }
        public string sname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public string sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tatuaje> tatuaje { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
